### ISSUE TITLE
user can add and save a poll question and 4 options

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/xero-2020#8]
We want each post to contain a question and 4 possible answers.

We are adding 5 new input fields:

- [ ] question
- [ ] answer 1
- [ ] answer 2
- [ ] answer 3
- [ ] answer 4

We'll add each one as a new text input (the white box you type words into) in _post.html_

### Part 1
- [ ] in post.html, add new `<input>` fields where the user can write their question and answers. You can copy and paste the 'message' input  which is already there.
- (Don't copy the whole form - we're just adding new inputs, just the one line staring with `<input`.  There should still only be one 'Post it!' button for the whole form.
- [ ] Give each new `<input>` fields a different class name, e.g. `class="question"`, `class="answer1"` and so on.
- [ ] Check: open localhost:3000/post.html and check your new input fields appear on the form.

### Part 2

If someone has already finished the issue **Clicking 'Post it!' should not go to a new page** then you need to do an extra step:
- [ ] in post.html, update the javascript so it sends the new form field to the server. (Look at the existing code for reference. You need to add one line of JavaScript code per new input.)
- For each input, you will need to add one line to the javascript in post.html. This will be very similar to the line that starts with `data.message =`… but will need to set `data.question` etc instead.
- If no-one has done **Clicking 'Post it!' should not go to a new page**, you can skip this step.

### Part 3

Now it's (hopefully) being sent to the server, we need to teach the server to look out for this new information.
- [x] We're now working in _index.js_
- [x] look for the code that is run when a user POSTS a new post to the server.
- [x] there is a line that writes the post's message to the console using `console.log(request.body.message);`. Add another line that logs request.body.question as well. ('question' needs to match whatever you saved it as in the data object back in post.html)
- [x] Restart the server, post a new post and check that your question now shows up in terminal/command prompt.
- [x] If the question is coming through, we can now save it. You do this by setting a new new name-value pair on the `post`. Your code might look like this:

```javascript
post.question = request.body.question;
```

- [x] now repeat these steps for the other 4 fields: answer1, answer2, answer3 and answer4.

### Part 4
- [x] Save some new posts then check how they look in raw form at http://localhost:3000/posts – each post should have a _question_ and four answers.
- [ ] modify feed.html so that each post displays the new fields. Find the line that creates the `postHTML` variable and add this to the HTML that's added:

```javascript
+ '  <div>question goes here</div>';
```

First check that that works - it should display 'question goes here' after every post.

Once that's working, change it to include the actual question `post.question` - you may need to use quotation marks to make it clear that you want the actual `post.question` and don't want it to literally say "post.question"

- [x] repeat for the other 4 new fields!

### notes

This task does not include updating the CSS look + feel of the post.html page. Just make it work, don't focus on making it pretty in this ticket.
